DROP TABLE IF EXISTS issue_history CASCADE;
DROP TABLE IF EXISTS issue_links CASCADE;
DROP TABLE IF EXISTS issue_watchers CASCADE;
DROP TABLE IF EXISTS issue_labels CASCADE;
DROP TABLE IF EXISTS labels CASCADE;
DROP TABLE IF EXISTS issues CASCADE;
